Why choose us
LiluUncharted/KMarketer pull request #3
Opened 2023-08-29 23:22 UTC by LiluUncharted

Mobile version I'll make later))

![image_2023-08-30_02-16-01](https://github.com/LiluUncharted/KMarketer/assets/141845795/25520a2b-9c45-400d-837d-0a708bf95d7a)

2023-08-30 12:30 UTC, IvanCeban requested changes
Great job! 
Just some naming suggesionts

2023-08-30 12:30 UTC, IvanCeban commented on index.html
> +                    <h2>WHY CHOOSE US</h2>
USe CSS to make text UPPERCASE instead of typing it in uppercase in html.

2023-08-30 12:30 UTC, IvanCeban commented on index.html
> +                    <div class="why-us-center-boxes">
I see your intention to use good class names. Great!

I suggest you to rethink the "why-us-center-boxes" namings.
Let's say what kind of data is that? If you take a closer look at the rest of the design you will notice that there are more of these cards.

So I suggest you to give each of the cards class card and use it for all sections in future.
The parent, the grid one contains cards. So you could give it a class called cards or cards-grid if you want to specify word "grid" there.
Inside each card you have "card header" and "card content". Here are the class names for them: card__header and card__content

Inside header you have icon and title.
So header__icn and header__title sound logical for their class names.

Basically you've chosen content agnostic class names as well. And you could use them for future elements. But "grid-item" doesn't tell us what kind of element is there. But "card" tells us that the element is a card and will look like a card. (it's a best practice to call cards elements like these)

2023-08-30 12:30 UTC, IvanCeban commented on index.html
> +            <div class="container-why-us">
I highly recommend you have just 1 container with max width. And this container to be used in all sections you have. 
In top-banner and in why-us same container wrapping the content of the sections

2023-08-30 12:30 UTC, IvanCeban commented on index.html
> +                        <img src="img/business_growing.svg" alt="business_growing">
I suggest you to choose names for icons but their content but not by their destination.

Ex: instead of `business_growing.svg ` just `briefcase.svg`
Instead of `national_top.svg` just `users.svg` or `people.svg`

This will allow you to use the same icon in another place and circumstances without losing the meaningfulness of its name.

2023-08-30 13:40 UTC, LiluUncharted commented on index.html
> +            <div class="container-why-us">
Max width in container (container-why-us-top) was useless and (container-why-us) was not used at all, I removed them.

2023-08-30 14:01 UTC, LiluUncharted commented on index.html
> +                        <img src="img/business_growing.svg" alt="business_growing">
Oh, u're right! Thanks, I made changes.

2023-08-30 14:06 UTC, LiluUncharted commented on index.html
> +                    <h2>WHY CHOOSE US</h2>
done

2023-08-30 14:37 UTC, LiluUncharted commented on index.html
> +                    <div class="why-us-center-boxes">
yes, I introduced new names of classes, thanks for review)) 
I hope, it turned out better this time

2023-09-01 08:00 UTC, IvanCeban requested changes
Good code and files structure and namings!
Please deal with containers as you till have some space for improvement there

2023-09-01 08:00 UTC, IvanCeban commented on index.html
> +                <div class="card-header">
you call the whole card a "card-header" which is not pretty intuitive. 
What if you call the card class just `card` and inside have a `card__header` for `img` and `h5` and a `card__content` for your `p`

2023-09-01 08:00 UTC, IvanCeban commented on index.html
> +            <div class="container-all">
Why do you need 2 containers here? One is more than enough. 

Even more, I highly recommend you use only 1 class `container` for all sections on your website. Same as I showed you on lessons. 
This container should limit the max width of whole section content and align it in center. That's it.

2023-09-01 12:30 UTC, IvanCeban approved these changes

2023-09-01 12:41 UTC, merged